project_id = "ryaiyvsklusqmvudpujv"

[functions.generate-contract]
verify_jwt = false

[functions.seed-data]
verify_jwt = false

[functions.seed-users]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.generate-lesson-plan]
verify_jwt = false