import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Save, Printer, Share2, FileDown, GraduationCap, X } from 'lucide-react';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import DOMPurify from 'dompurify';
import { toast } from '@/hooks/use-toast';

interface LessonPlanPreviewProps {
  content: string;
  onSave: () => void;
  onClose?: () => void;
  isSaving: boolean;
  isSaved?: boolean;
  teacherName?: string;
  className?: string;
  subjectName?: string;
}

function cleanContent(raw: string): string {
  let cleaned = raw
    .replace(/^```html\s*/i, '')
    .replace(/^```\w*\s*/gm, '')
    .replace(/```\s*$/gm, '')
    .trim();

  // Remove any AI-generated <h1> titles
  cleaned = cleaned.replace(/<h1[^>]*>[\s\S]*?<\/h1>/gi, '');

  // Remove duplicated header-info blocks generated by AI
  cleaned = cleaned.replace(/<div[^>]*class="header-info"[^>]*>[\s\S]*?<\/div>/gi, '');

  // Remove any "INFORMAÇÕES GERAIS" section entirely (h2 + following list/paragraph until next h2)
  cleaned = cleaned.replace(/<h2[^>]*>\s*(?:📌\s*)?INFORMA[ÇC][ÕO]ES\s+GERAIS\s*<\/h2>[\s\S]*?(?=<h2)/gi, '');

  // Remove any block containing school/professor/class/discipline info within first 2000 chars
  const first2000 = cleaned.substring(0, 2000);
  const rest = cleaned.substring(2000);
  const cleanedFirst = first2000
    .replace(/<(?:div|table|section|header|ul)[^>]*>[\s\S]*?(?:Escola\s*:|Professor\s*:|Turma\s*:|Classe\s*:|Disciplina\s*:|Data\s+das?\s+Aulas?\s*:)[\s\S]*?<\/(?:div|table|section|header|ul)>/gi, '')
    .replace(/<p[^>]*>[\s\S]*?(?:Escola\s*:|Professor\s*:|Turma\s*:|Classe\/Turma\s*:|Disciplina\s*:)[\s\S]*?<\/p>/gi, '')
    // Remove standalone list items with professor/turma/disciplina info
    .replace(/<li[^>]*>[\s\S]*?(?:Professor\s*:|Turma\s*:|Classe\s*:|Disciplina\s*:|Data\s+das?\s+Aulas?\s*:|Tema\s*:|Princ[ií]pios?\s+da\s+AEP)[\s\S]*?<\/li>/gi, '')
    // Remove any orphaned <ul> that became empty after removing <li>
    .replace(/<ul[^>]*>\s*<\/ul>/gi, '');
  cleaned = cleanedFirst + rest;

  return cleaned.trim();
}

const A4_STYLES = `
@import url('https://fonts.googleapis.com/css2?family=Work+Sans:wght@300;400;500;600;700;800&display=swap');
@page {
  size: A4;
  margin: 20mm 14mm 18mm 14mm;
}
* { box-sizing: border-box; }
body {
  font-family: 'Work Sans', sans-serif;
  font-weight: 300;
  color: hsl(20 14.3% 8%);
  margin: 0;
  padding: 0;
  font-size: 12px;
  line-height: 1.7;
  -webkit-print-color-adjust: exact;
  print-color-adjust: exact;
}
.page-header {
  padding-bottom: 10px;
  margin-bottom: 14px;
  border-bottom: 2px solid hsl(140 37% 28%);
}
.page-header-top {
  display: flex;
  align-items: center;
  gap: 12px;
}
.page-header-logo {
  width: 38px;
  height: 38px;
  background: linear-gradient(135deg, hsl(140 37% 28%), hsl(140 25% 39%));
  border-radius: 8px;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}
.page-header-title {
  font-size: 15px;
  font-weight: 800;
  color: hsl(140 37% 28%);
  margin: 0;
}
.page-header-sub {
  font-size: 9px;
  color: hsl(140 25% 39%);
  margin: 0;
  font-weight: 500;
}
.page-header-right {
  margin-left: auto;
  text-align: right;
}
.page-header-right p:first-child {
  font-size: 12px;
  font-weight: 700;
  color: hsl(20 14.3% 8%);
  margin: 0;
}
.page-header-right p:last-child {
  font-size: 9px;
  color: hsl(20 14.3% 28%);
  margin: 0;
}
.page-header-meta {
  display: flex;
  gap: 18px;
  font-size: 10px;
  color: hsl(20 14.3% 18%);
  margin-top: 6px;
  padding-top: 5px;
}
.page-header-meta strong {
  font-weight: 600;
}
.running-footer {
  position: fixed;
  bottom: 7mm;
  left: 14mm;
  right: 14mm;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding-top: 2.5mm;
  font-size: 8px;
  color: hsl(20 14.3% 8% / 0.6);
  border-top: 0.5px solid hsl(140 10% 82%);
}
.content {
  padding: 0;
}
h1 { display: none; }
h2 { font-size: 13px; font-weight: 700; color: hsl(140 37% 28%); margin: 14px 0 6px; border-bottom: 1.5px solid hsl(140 37% 28% / 0.3); padding-bottom: 3px; }
h3 { font-size: 12px; font-weight: 600; color: hsl(140 25% 39%); margin: 11px 0 5px; }
h4 { font-size: 11px; font-weight: 600; color: hsl(20 14.3% 12%); margin: 9px 0 4px; }
p, li { font-size: 11px; }
p { margin: 5px 0; }
ul, ol { padding-left: 20px; margin: 5px 0; }
li { margin: 3px 0; }
strong { font-weight: 600; }
blockquote { border-left: 3px solid hsl(140 37% 28%); margin: 7px 0; padding: 7px 12px; background: hsl(140 25% 96%); font-style: italic; }
table { border-collapse: collapse; width: 100%; margin: 10px 0; }
th { background: hsl(140 37% 28%); color: white; padding: 6px 8px; text-align: left; font-size: 10px; font-weight: 600; }
td { border: 1px solid hsl(140 10% 82%); padding: 5px 8px; font-size: 10px; }
tr:nth-child(even) td { background: hsl(140 10% 97%); }
hr { border: none; border-top: 1px solid hsl(140 10% 82%); margin: 10px 0; }
@media print {
  .no-print { display: none !important; }
  body { font-size: 11px; }
}
`;

const getHeaderHtml = (teacherName: string, className: string, subjectName: string) => `
<div class="page-header">
  <div class="page-header-top">
    <div class="page-header-logo">
      <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z"/><path d="M22 10v6"/><path d="M6 12.5V16a6 3 0 0 0 12 0v-3.5"/></svg>
    </div>
    <div>
      <p class="page-header-title">ESCOLA REVIVA</p>
      <p class="page-header-sub">SiGER - Sistema de Gestão Escolar Reviva</p>
    </div>
    <div class="page-header-right">
      <p>PLANO DE AULA AEP</p>
      <p>Abordagem Educacional por Princípios</p>
    </div>
  </div>
  <div class="page-header-meta">
    ${teacherName ? `<span><strong>Professor:</strong> ${teacherName}</span>` : ''}
    ${className ? `<span><strong>Turma:</strong> ${className}</span>` : ''}
    ${subjectName ? `<span><strong>Disciplina:</strong> ${subjectName}</span>` : ''}
  </div>
</div>
`;

export function LessonPlanPreview({ content, onSave, onClose, isSaving, isSaved = false, teacherName = '', className = '', subjectName = '' }: LessonPlanPreviewProps) {
  const [showCloseConfirm, setShowCloseConfirm] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);

  const cleaned = cleanContent(content);
  const sanitizedContent = DOMPurify.sanitize(cleaned);

  const dateOnly = new Date().toLocaleDateString('pt-MZ', { day: '2-digit', month: '2-digit', year: 'numeric' });
  const dateTime = new Date().toLocaleString('pt-MZ', { day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit' });

  const getFullHtml = () => `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Plano de Aula AEP - Escola Reviva</title>
<style>${A4_STYLES}</style>
</head>
<body>
  <div class="running-footer">
    <span>SiGER - Sistema de Gestão Escolar Reviva</span>
    <span>${dateOnly}</span>
  </div>

  <main class="content">
    ${getHeaderHtml(teacherName, className, subjectName)}
    ${sanitizedContent}
  </main>
</body>
</html>`;

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      toast({ title: 'Erro', description: 'Permita pop-ups para imprimir.', variant: 'destructive' });
      return;
    }
    printWindow.document.write(getFullHtml());
    printWindow.document.close();
    printWindow.onafterprint = () => printWindow.close();
    setTimeout(() => printWindow.print(), 350);
  };

  const handleDownloadPdf = async () => {
    setIsDownloading(true);
    try {
      const html2pdf = (await import('html2pdf.js')).default;

      // Build content WITHOUT the fixed footer (it won't render in html2canvas)
      const wrapper = document.createElement('div');
      const styleEl = document.createElement('style');
      styleEl.textContent = A4_STYLES + `
        .running-footer { display: none !important; }
      `;
      wrapper.appendChild(styleEl);

      // Add header + content
      const contentDiv = document.createElement('div');
      contentDiv.innerHTML = `
        <main class="content">
          ${getHeaderHtml(teacherName, className, subjectName)}
          ${sanitizedContent}
        </main>
      `;
      wrapper.appendChild(contentDiv);
      document.body.appendChild(wrapper);

      const fileName = `Plano_AEP_${(subjectName || 'Aula').replace(/\s+/g, '_')}_${dateOnly.replace(/\//g, '-')}.pdf`;

      // Top margin increased to leave room for repeated header on subsequent pages
      const marginTop = 20;
      const marginBottom = 18;
      const marginLeft = 14;
      const marginRight = 14;

      const worker = html2pdf().set({
        margin: [marginTop, marginRight, marginBottom, marginLeft],
        filename: fileName,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2, useCORS: true, logging: false },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        pagebreak: { mode: ['avoid-all', 'css', 'legacy'] },
      }).from(wrapper);

      // Use thennable to access jsPDF instance and add footer with page numbers
      await (worker.toPdf() as any).get('pdf').then((pdf: any) => {
        const totalPages = pdf.internal.getNumberOfPages();
        const pageWidth = pdf.internal.pageSize.getWidth();
        const pageHeight = pdf.internal.pageSize.getHeight();

        for (let i = 1; i <= totalPages; i++) {
          pdf.setPage(i);

          // Footer line
          pdf.setDrawColor(180, 200, 180);
          pdf.setLineWidth(0.3);
          pdf.line(marginLeft, pageHeight - 12, pageWidth - marginRight, pageHeight - 12);

          // Footer text - left
          pdf.setFontSize(7);
          pdf.setTextColor(120, 120, 120);
          pdf.text('SiGER - Sistema de Gestão Escolar Reviva', marginLeft, pageHeight - 8);

          // Footer text - center (date)
          const dateText = dateOnly;
          const dateWidth = pdf.getStringUnitWidth(dateText) * 7 / pdf.internal.scaleFactor;
          pdf.text(dateText, (pageWidth - dateWidth) / 2, pageHeight - 8);

          // Footer text - right (page number)
          const pageText = `Página ${i} de ${totalPages}`;
          const pageTextWidth = pdf.getStringUnitWidth(pageText) * 7 / pdf.internal.scaleFactor;
          pdf.text(pageText, pageWidth - marginRight - pageTextWidth, pageHeight - 8);
        }
      }).save();

      document.body.removeChild(wrapper);
      toast({ title: 'PDF descarregado', description: fileName });
    } catch (error) {
      console.error('Erro ao gerar PDF:', error);
      toast({ title: 'Erro', description: 'Não foi possível gerar o PDF. Tente imprimir em vez disso.', variant: 'destructive' });
    } finally {
      setIsDownloading(false);
    }
  };

  const handleSharePdf = async () => {
    const text = 'Plano de Aula AEP pronto para partilha em PDF. Use o ícone de download para gerar o PDF e partilhar.';
    if (navigator.share) {
      try {
        await navigator.share({ title: 'Plano de Aula AEP', text });
        return;
      } catch { /* user cancelled */ }
    }
    await navigator.clipboard.writeText(text);
    toast({ title: 'Copiado', description: 'Instrução de partilha copiada para a área de transferência.' });
  };

  const handleClose = () => {
    if (!isSaved && onClose) {
      setShowCloseConfirm(true);
    } else {
      onClose?.();
    }
  };

  const handleCloseConfirmed = () => {
    setShowCloseConfirm(false);
    onClose?.();
  };

  const handleSaveAndClose = () => {
    onSave();
    setShowCloseConfirm(false);
    // onClose will be triggered after save success by the parent
  };

  return (
    <div className="space-y-0">
      <div className="flex items-center justify-between px-4 py-2 bg-muted/50 rounded-t-lg border border-b-0 border-border">
        <p className="text-xs text-muted-foreground font-medium">Documento A4 · {dateOnly}</p>
        <div className="flex items-center gap-1">
          <Button variant="ghost" size="icon" onClick={handlePrint} title="Imprimir" className="h-8 w-8">
            <Printer className="h-4 w-4" />
          </Button>
          <Button variant="ghost" size="icon" onClick={handleDownloadPdf} disabled={isDownloading} title="Descarregar PDF" className="h-8 w-8">
            <FileDown className="h-4 w-4" />
          </Button>
          <Button variant="ghost" size="icon" onClick={handleSharePdf} title="Partilhar" className="h-8 w-8">
            <Share2 className="h-4 w-4" />
          </Button>
          <div className="w-px h-5 bg-border mx-1" />
          <Button size="sm" onClick={onSave} disabled={isSaving} className="h-8 text-xs gap-1">
            <Save className="h-3.5 w-3.5" /> Guardar
          </Button>
          {onClose && (
            <Button variant="ghost" size="icon" onClick={handleClose} title="Fechar pré-visualização" className="h-8 w-8 text-muted-foreground hover:text-destructive">
              <X className="h-4 w-4" />
            </Button>
          )}
        </div>
      </div>

      <div className="bg-white rounded-b-lg border border-border shadow-lg overflow-hidden">
        <div className="bg-gradient-to-r from-primary to-secondary px-6 py-3">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 bg-background/20 rounded-lg flex items-center justify-center shrink-0">
              <GraduationCap className="w-4 h-4 text-primary-foreground" />
            </div>
            <div className="min-w-0 flex-1">
              <h2 className="text-sm font-extrabold text-primary-foreground tracking-tight">ESCOLA REVIVA</h2>
              <p className="text-[10px] text-primary-foreground/80 font-medium">SiGER - Sistema de Gestão Escolar Reviva</p>
            </div>
            <div className="text-right hidden sm:block">
              <p className="text-[12px] font-bold text-primary-foreground">PLANO DE AULA AEP</p>
              <p className="text-[10px] text-primary-foreground/80">Abordagem Educacional por Princípios</p>
            </div>
          </div>
        </div>

        <div className="px-6 sm:px-10 py-5 sm:py-6 min-h-[500px] overflow-x-hidden">
          <div
            className="max-w-none prose prose-sm"
            style={{
              fontFamily: "'Work Sans', sans-serif",
              fontWeight: 300,
              color: 'hsl(20 14.3% 8%)',
              fontSize: '11px',
              lineHeight: 1.7,
            }}
            dangerouslySetInnerHTML={{ __html: sanitizedContent }}
          />
        </div>

        <div className="flex items-center justify-between px-6 sm:px-10 py-2 text-[10px] text-foreground/70">
          <span>SiGER - Sistema de Gestão Escolar Reviva</span>
          <span>{dateOnly}</span>
        </div>
      </div>

      <AlertDialog open={showCloseConfirm} onOpenChange={setShowCloseConfirm}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Plano não guardado</AlertDialogTitle>
            <AlertDialogDescription>
              O plano de aula ainda não foi guardado nos Arquivos. Deseja guardar antes de fechar?
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel onClick={handleCloseConfirmed}>Fechar sem guardar</AlertDialogCancel>
            <AlertDialogAction onClick={handleSaveAndClose}>Guardar e fechar</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
