import React from 'react';
import { Button } from '@/components/ui/button';
import { Save, Printer, Share2, FileDown, GraduationCap } from 'lucide-react';
import DOMPurify from 'dompurify';
import { toast } from '@/hooks/use-toast';

interface LessonPlanPreviewProps {
  content: string;
  onSave: () => void;
  isSaving: boolean;
  teacherName?: string;
  className?: string;
  subjectName?: string;
}

function cleanContent(raw: string): string {
  let cleaned = raw
    .replace(/^```html\s*/i, '')
    .replace(/^```\w*\s*/gm, '')
    .replace(/```\s*$/gm, '')
    .trim();

  // Remove any AI-generated <h1> titles (the header is in the UI component)
  cleaned = cleaned.replace(/<h1[^>]*>[\s\S]*?<\/h1>/gi, '');

  // Remove duplicated header-info blocks generated by AI
  cleaned = cleaned.replace(/<div[^>]*class="header-info"[^>]*>[\s\S]*?<\/div>/gi, '');

  // Remove any block (div, table, p, section, header) containing school/professor/class/discipline info
  // within the first 1500 chars to avoid stripping legitimate content deeper in the document
  const first1500 = cleaned.substring(0, 1500);
  const rest = cleaned.substring(1500);
  const cleanedFirst = first1500
    .replace(/<(?:div|table|section|header)[^>]*>[\s\S]*?(?:Escola\s*:|Professor\s*:|Turma\s*:|Classe\s*:|Disciplina\s*:)[\s\S]*?<\/(?:div|table|section|header)>/gi, '')
    .replace(/<p[^>]*>[\s\S]*?(?:Escola\s*:|Professor\s*:|Turma\s*:|Classe\/Turma\s*:|Disciplina\s*:)[\s\S]*?<\/p>/gi, '');
  cleaned = cleanedFirst + rest;

  return cleaned.trim();
}

const A4_STYLES = `
@import url('https://fonts.googleapis.com/css2?family=Work+Sans:wght@300;400;500;600;700;800&display=swap');
@page {
  size: A4;
  margin: 22mm 14mm 18mm 14mm;
}
* { box-sizing: border-box; }
body {
  font-family: 'Work Sans', sans-serif;
  font-weight: 300;
  color: hsl(20 14.3% 8%);
  margin: 0;
  padding: 0;
  font-size: 12px;
  line-height: 1.7;
  -webkit-print-color-adjust: exact;
  print-color-adjust: exact;
}
.running-header {
  position: fixed;
  top: 9mm;
  left: 14mm;
  right: 14mm;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding-bottom: 3mm;
  font-size: 10px;
  color: hsl(20 14.3% 8%);
}
.running-footer {
  position: fixed;
  bottom: 7mm;
  left: 14mm;
  right: 14mm;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding-top: 2.5mm;
  font-size: 9px;
  color: hsl(20 14.3% 8% / 0.8);
}
.content {
  padding: 8mm 0 14mm;
}
.header-bar {
  padding-bottom: 10px;
  margin-bottom: 16px;
}
.header-top {
  display: flex;
  align-items: center;
  gap: 12px;
}
.header-logo {
  width: 40px;
  height: 40px;
  background: linear-gradient(135deg, hsl(140 37% 28%), hsl(140 25% 39%));
  border-radius: 8px;
  display: flex;
  align-items: center;
  justify-content: center;
}
.header-title {
  font-size: 16px;
  font-weight: 800;
  color: hsl(140 37% 28%);
  margin: 0;
}
.header-sub {
  font-size: 10px;
  color: hsl(140 25% 39%);
  margin: 0;
  font-weight: 500;
}
h1 { font-size: 15px; font-weight: 700; color: hsl(140 37% 28%); margin: 14px 0 7px; border-bottom: 2px solid hsl(140 37% 28%); padding-bottom: 4px; }
h2 { font-size: 13px; font-weight: 600; color: hsl(140 37% 28%); margin: 13px 0 6px; }
h3 { font-size: 12px; font-weight: 600; color: hsl(140 25% 39%); margin: 11px 0 5px; }
h4 { font-size: 11px; font-weight: 600; color: hsl(20 14.3% 12%); margin: 9px 0 4px; }
p, li { font-size: 11px; }
p { margin: 5px 0; }
ul, ol { padding-left: 20px; margin: 5px 0; }
li { margin: 3px 0; }
strong { font-weight: 600; }
blockquote { border-left: 3px solid hsl(140 37% 28%); margin: 7px 0; padding: 7px 12px; background: hsl(140 25% 96%); font-style: italic; }
table { border-collapse: collapse; width: 100%; margin: 10px 0; }
th { background: hsl(140 37% 28%); color: white; padding: 6px 8px; text-align: left; font-size: 11px; font-weight: 600; }
td { border: 1px solid hsl(140 10% 82%); padding: 6px 8px; font-size: 11px; }
tr:nth-child(even) td { background: hsl(140 10% 97%); }
hr { border: none; border-top: 1px solid hsl(140 10% 82%); margin: 10px 0; }
@media print {
  .no-print { display: none !important; }
  body { font-size: 12px; }
  h1 { font-size: 16px; }
  h2 { font-size: 14px; }
  h3 { font-size: 13px; }
  h4 { font-size: 12px; }
  p, li { font-size: 12px; }
}
`;

const getHeaderHtml = (teacherName: string, className: string, subjectName: string) => `
<div class="header-bar">
  <div class="header-top">
    <div class="header-logo">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z"/><path d="M22 10v6"/><path d="M6 12.5V16a6 3 0 0 0 12 0v-3.5"/></svg>
    </div>
    <div>
      <p class="header-title">ESCOLA REVIVA</p>
      <p class="header-sub">SiGER - Sistema de Gestão Escolar Reviva</p>
    </div>
    <div style="margin-left:auto;text-align:right;">
      <p style="font-size:12px;font-weight:700;color:hsl(20 14.3% 8%);margin:0;">PLANO DE AULA AEP</p>
      <p style="font-size:10px;color:hsl(20 14.3% 28%);margin:0;">Abordagem Educacional por Princípios</p>
    </div>
  </div>
  <div style="display:flex;gap:18px;font-size:11px;color:hsl(20 14.3% 18%);margin-top:8px;padding-top:6px;border-top:1px solid hsl(140 10% 82%);">
    ${teacherName ? `<span><strong>Professor:</strong> ${teacherName}</span>` : ''}
    ${className ? `<span><strong>Turma:</strong> ${className}</span>` : ''}
    ${subjectName ? `<span><strong>Disciplina:</strong> ${subjectName}</span>` : ''}
  </div>
</div>
`;

export function LessonPlanPreview({ content, onSave, isSaving, teacherName = '', className = '', subjectName = '' }: LessonPlanPreviewProps) {
  const cleaned = cleanContent(content);
  const sanitizedContent = DOMPurify.sanitize(cleaned);

  const dateOnly = new Date().toLocaleDateString('pt-MZ', { day: '2-digit', month: '2-digit', year: 'numeric' });
  const dateTime = new Date().toLocaleString('pt-MZ', { day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit' });

  const getFullHtml = () => `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Plano de Aula AEP - Escola Reviva</title>
<style>${A4_STYLES}</style>
</head>
<body>
  <div class="running-header">
    <span>Plano de Aula AEP - Escola Reviva</span>
    <span>${dateTime}</span>
  </div>

  <div class="running-footer">
    <span>SiGER - Sistema de Gestão Escolar Reviva</span>
    <span>${dateOnly}</span>
  </div>

  <main class="content">
    ${getHeaderHtml(teacherName, className, subjectName)}
    ${sanitizedContent}
  </main>
</body>
</html>`;

  const openPrintWindow = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      toast({ title: 'Erro', description: 'Permita pop-ups para imprimir ou descarregar PDF.', variant: 'destructive' });
      return null;
    }

    printWindow.document.write(getFullHtml());
    printWindow.document.close();
    return printWindow;
  };

  const handlePrint = () => {
    const printWindow = openPrintWindow();
    if (!printWindow) return;
    printWindow.onafterprint = () => printWindow.close();
    setTimeout(() => printWindow.print(), 350);
  };

  const handleDownloadPdf = () => {
    const printWindow = openPrintWindow();
    if (!printWindow) return;
    toast({ title: 'PDF', description: 'Na impressão, escolha "Guardar como PDF" e desactive os cabeçalhos/rodapés do navegador.' });
    setTimeout(() => printWindow.print(), 350);
  };

  const handleSharePdf = async () => {
    const text = 'Plano de Aula AEP pronto para partilha em PDF. Use o ícone de download para gerar o PDF e partilhar.';
    if (navigator.share) {
      try {
        await navigator.share({ title: 'Plano de Aula AEP', text });
        return;
      } catch {
        // user cancelled
      }
    }

    await navigator.clipboard.writeText(text);
    toast({ title: 'Copiado', description: 'Instrução de partilha copiada para a área de transferência.' });
  };

  return (
    <div className="space-y-0">
      <div className="flex items-center justify-between px-4 py-2 bg-muted/50 rounded-t-lg border border-b-0 border-border">
        <p className="text-xs text-muted-foreground font-medium">Documento A4 · {dateOnly}</p>
        <div className="flex items-center gap-1">
          <Button variant="ghost" size="icon" onClick={handlePrint} title="Imprimir" className="h-8 w-8">
            <Printer className="h-4 w-4" />
          </Button>
          <Button variant="ghost" size="icon" onClick={handleDownloadPdf} title="Descarregar PDF" className="h-8 w-8">
            <FileDown className="h-4 w-4" />
          </Button>
          <Button variant="ghost" size="icon" onClick={handleSharePdf} title="Partilhar" className="h-8 w-8">
            <Share2 className="h-4 w-4" />
          </Button>
          <div className="w-px h-5 bg-border mx-1" />
          <Button size="sm" onClick={onSave} disabled={isSaving} className="h-8 text-xs gap-1">
            <Save className="h-3.5 w-3.5" /> Guardar
          </Button>
        </div>
      </div>

      <div className="bg-white rounded-b-lg border border-border shadow-lg overflow-hidden">
        <div className="bg-gradient-to-r from-primary to-secondary px-6 py-3">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 bg-background/20 rounded-lg flex items-center justify-center shrink-0">
              <GraduationCap className="w-4 h-4 text-primary-foreground" />
            </div>
            <div className="min-w-0 flex-1">
              <h2 className="text-sm font-extrabold text-primary-foreground tracking-tight">ESCOLA REVIVA</h2>
              <p className="text-[10px] text-primary-foreground/80 font-medium">SiGER - Sistema de Gestão Escolar Reviva</p>
            </div>
            <div className="text-right hidden sm:block">
              <p className="text-[12px] font-bold text-primary-foreground">PLANO DE AULA AEP</p>
              <p className="text-[10px] text-primary-foreground/80">Abordagem Educacional por Princípios</p>
            </div>
          </div>
        </div>

        <div className="px-6 sm:px-10 py-5 sm:py-6 min-h-[500px] overflow-x-hidden">
          <div
            className="max-w-none prose prose-sm"
            style={{
              fontFamily: "'Work Sans', sans-serif",
              fontWeight: 300,
              color: 'hsl(20 14.3% 8%)',
              fontSize: '11px',
              lineHeight: 1.7,
            }}
            dangerouslySetInnerHTML={{ __html: sanitizedContent }}
          />
        </div>

        <div className="flex items-center justify-between px-6 sm:px-10 py-2 text-[10px] text-foreground/70">
          <span>SiGER - Sistema de Gestão Escolar Reviva</span>
          <span>{dateOnly}</span>
        </div>
      </div>
    </div>
  );
}
