-- Create enrollment type enum if not exists
DO $$ BEGIN
    CREATE TYPE enrollment_type AS ENUM ('NEW', 'RENEWAL');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Update student_enrollments table
ALTER TABLE public.student_enrollments 
ADD COLUMN IF NOT EXISTS enrollment_type enrollment_type DEFAULT 'NEW',
ADD COLUMN IF NOT EXISTS previous_enrollment_id BIGINT REFERENCES public.student_enrollments(id);

-- Create education_levels table
CREATE TABLE IF NOT EXISTS public.education_levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE, -- e.g., 'Primário', 'Secundário Geral', 'Secundário Técnico'
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Insert default levels
INSERT INTO public.education_levels (name) VALUES 
('Educação Pré-Escolar'),
('Ensino Primário (1ª - 6ª Classe)'),
('Ensino Secundário (7ª - 12ª Classe)')
ON CONFLICT (name) DO NOTHING;

-- Create education_level_fees table
CREATE TABLE IF NOT EXISTS public.education_level_fees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    education_level_id BIGINT REFERENCES public.education_levels(id) ON DELETE CASCADE,
    academic_year_id BIGINT REFERENCES public.academic_years(id) ON DELETE CASCADE,
    enrollment_fee NUMERIC(15,2) NOT NULL DEFAULT 0,
    monthly_fee NUMERIC(15,2) NOT NULL DEFAULT 0,
    re_enrollment_fee NUMERIC(15,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    UNIQUE(education_level_id, academic_year_id)
);

-- Create enrollment_periods table
CREATE TABLE IF NOT EXISTS public.enrollment_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year_id BIGINT REFERENCES public.academic_years(id) ON DELETE CASCADE,
    education_level_id BIGINT REFERENCES public.education_levels(id) ON DELETE CASCADE,
    type enrollment_type NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Grants
GRANT SELECT ON public.education_levels TO authenticated;
GRANT SELECT ON public.education_level_fees TO authenticated;
GRANT SELECT ON public.enrollment_periods TO authenticated;

GRANT ALL ON public.education_levels TO service_role;
GRANT ALL ON public.education_level_fees TO service_role;
GRANT ALL ON public.enrollment_periods TO service_role;

-- Special grants for admin/diretoria
GRANT ALL ON public.education_level_fees TO authenticated;
GRANT ALL ON public.enrollment_periods TO authenticated;

-- Enable RLS
ALTER TABLE public.education_levels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.education_level_fees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrollment_periods ENABLE ROW LEVEL SECURITY;

-- Policies for education_levels
CREATE POLICY "Anyone authenticated can view education levels" 
ON public.education_levels FOR SELECT TO authenticated USING (true);

-- Policies for education_level_fees
CREATE POLICY "Anyone authenticated can view fees" 
ON public.education_level_fees FOR SELECT TO authenticated USING (true);

CREATE POLICY "Only Admin and Diretoria can manage fees" 
ON public.education_level_fees FOR ALL TO authenticated 
USING (
    EXISTS (
        SELECT 1 FROM public.user_roles 
        WHERE user_id = auth.uid() AND role::text IN ('ADMIN', 'DIRETORIA')
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.user_roles 
        WHERE user_id = auth.uid() AND role::text IN ('ADMIN', 'DIRETORIA')
    )
);

-- Policies for enrollment_periods
CREATE POLICY "Anyone authenticated can view periods" 
ON public.enrollment_periods FOR SELECT TO authenticated USING (true);

CREATE POLICY "Only Admin and Diretoria can manage periods" 
ON public.enrollment_periods FOR ALL TO authenticated 
USING (
    EXISTS (
        SELECT 1 FROM public.user_roles 
        WHERE user_id = auth.uid() AND role::text IN ('ADMIN', 'DIRETORIA')
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.user_roles 
        WHERE user_id = auth.uid() AND role::text IN ('ADMIN', 'DIRETORIA')
    )
);

-- Trigger for updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_education_level_fees_updated_at
BEFORE UPDATE ON public.education_level_fees
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER tr_enrollment_periods_updated_at
BEFORE UPDATE ON public.enrollment_periods
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
