-- =====================================================
-- SISTEMA DE COBRANÇA INTELIGENTE - SGE REVIVA
-- =====================================================

-- Enum para status de acordo/negociação
CREATE TYPE public.payment_agreement_status AS ENUM (
  'PENDENTE',
  'ATIVO',
  'CUMPRIDO',
  'QUEBRADO',
  'CANCELADO'
);

-- Enum para tipo de comunicação
CREATE TYPE public.communication_type AS ENUM (
  'WHATSAPP',
  'SMS',
  'TELEFONE',
  'EMAIL',
  'PRESENCIAL'
);

-- Enum para status de comunicação
CREATE TYPE public.communication_status AS ENUM (
  'ENVIADO',
  'ENTREGUE',
  'LIDO',
  'FALHOU',
  'AGENDADO'
);

-- Enum para tipo de reminder/lembrete
CREATE TYPE public.reminder_type AS ENUM (
  'VENCIMENTO_PROXIMO',
  'DIA_VENCIMENTO',
  'ATRASO_LEVE',
  'ATRASO_MODERADO',
  'ATRASO_GRAVE',
  'PARCELA_ACORDO'
);

-- =====================================================
-- TABELA: Acordos de Pagamento / Negociações
-- =====================================================
CREATE TABLE public.payment_agreements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tuition_fee_id BIGINT NOT NULL REFERENCES public.tuition_fees(id) ON DELETE CASCADE,
  student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  
  -- Valores originais
  original_amount NUMERIC(10,2) NOT NULL,
  
  -- Desconto aplicado
  discount_percent NUMERIC(5,2) DEFAULT 0,
  discount_amount NUMERIC(10,2) DEFAULT 0,
  
  -- Valor final acordado
  agreed_amount NUMERIC(10,2) NOT NULL,
  
  -- Parcelamento
  installments INTEGER DEFAULT 1,
  installment_amount NUMERIC(10,2),
  
  -- Data prometida (para promessa simples)
  promised_date DATE,
  
  -- Status
  status payment_agreement_status DEFAULT 'PENDENTE',
  
  -- Observações
  notes TEXT,
  
  -- Auditoria
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- =====================================================
-- TABELA: Parcelas do Acordo
-- =====================================================
CREATE TABLE public.agreement_installments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agreement_id BIGINT NOT NULL REFERENCES public.payment_agreements(id) ON DELETE CASCADE,
  
  installment_number INTEGER NOT NULL,
  amount NUMERIC(10,2) NOT NULL,
  due_date DATE NOT NULL,
  
  -- Status
  paid BOOLEAN DEFAULT false,
  paid_at TIMESTAMP WITH TIME ZONE,
  payment_method TEXT,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- =====================================================
-- TABELA: Histórico de Comunicações
-- =====================================================
CREATE TABLE public.communication_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Referência (pode ser propina ou acordo)
  tuition_fee_id BIGINT REFERENCES public.tuition_fees(id) ON DELETE SET NULL,
  agreement_id BIGINT REFERENCES public.payment_agreements(id) ON DELETE SET NULL,
  student_id BIGINT REFERENCES public.students(id) ON DELETE CASCADE,
  
  -- Tipo e canal
  communication_type communication_type NOT NULL,
  
  -- Destinatário
  recipient_name TEXT NOT NULL,
  recipient_phone TEXT,
  recipient_email TEXT,
  
  -- Mensagem
  message_template TEXT,
  message_content TEXT NOT NULL,
  
  -- Status
  status communication_status DEFAULT 'ENVIADO',
  
  -- External IDs (Evolution API, SMS gateway, etc.)
  external_id TEXT,
  external_response JSONB,
  
  -- Timestamps
  scheduled_at TIMESTAMP WITH TIME ZONE,
  sent_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  delivered_at TIMESTAMP WITH TIME ZONE,
  read_at TIMESTAMP WITH TIME ZONE,
  
  -- Auditoria
  sent_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- =====================================================
-- TABELA: Lembretes Automáticos Agendados
-- =====================================================
CREATE TABLE public.scheduled_reminders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  tuition_fee_id BIGINT REFERENCES public.tuition_fees(id) ON DELETE CASCADE,
  agreement_id BIGINT REFERENCES public.payment_agreements(id) ON DELETE CASCADE,
  student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  
  reminder_type reminder_type NOT NULL,
  
  -- Agendamento
  scheduled_for TIMESTAMP WITH TIME ZONE NOT NULL,
  
  -- Canal preferido
  channel communication_type DEFAULT 'WHATSAPP',
  
  -- Status
  processed BOOLEAN DEFAULT false,
  processed_at TIMESTAMP WITH TIME ZONE,
  communication_id BIGINT REFERENCES public.communication_history(id),
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- =====================================================
-- ÍNDICES
-- =====================================================
CREATE INDEX idx_agreements_student ON public.payment_agreements(student_id);
CREATE INDEX idx_agreements_status ON public.payment_agreements(status);
CREATE INDEX idx_agreements_tuition ON public.payment_agreements(tuition_fee_id);
CREATE INDEX idx_installments_agreement ON public.agreement_installments(agreement_id);
CREATE INDEX idx_installments_due ON public.agreement_installments(due_date) WHERE NOT paid;
CREATE INDEX idx_comm_history_student ON public.communication_history(student_id);
CREATE INDEX idx_comm_history_status ON public.communication_history(status);
CREATE INDEX idx_reminders_scheduled ON public.scheduled_reminders(scheduled_for) WHERE NOT processed;

-- =====================================================
-- RLS POLICIES
-- =====================================================

-- payment_agreements
ALTER TABLE public.payment_agreements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Finance can manage agreements"
  ON public.payment_agreements FOR ALL
  USING (has_any_role(auth.uid(), ARRAY['ADMIN'::app_role, 'DIRETORIA'::app_role, 'FINANCEIRO'::app_role, 'SECRETARIA'::app_role]));

CREATE POLICY "Finance can view agreements"
  ON public.payment_agreements FOR SELECT
  USING (has_any_role(auth.uid(), ARRAY['ADMIN'::app_role, 'DIRETORIA'::app_role, 'FINANCEIRO'::app_role, 'SECRETARIA'::app_role]));

-- agreement_installments
ALTER TABLE public.agreement_installments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Finance can manage installments"
  ON public.agreement_installments FOR ALL
  USING (EXISTS (
    SELECT 1 FROM public.payment_agreements pa 
    WHERE pa.id = agreement_id 
    AND has_any_role(auth.uid(), ARRAY['ADMIN'::app_role, 'DIRETORIA'::app_role, 'FINANCEIRO'::app_role, 'SECRETARIA'::app_role])
  ));

CREATE POLICY "Finance can view installments"
  ON public.agreement_installments FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM public.payment_agreements pa 
    WHERE pa.id = agreement_id 
    AND has_any_role(auth.uid(), ARRAY['ADMIN'::app_role, 'DIRETORIA'::app_role, 'FINANCEIRO'::app_role, 'SECRETARIA'::app_role])
  ));

-- communication_history
ALTER TABLE public.communication_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Finance can manage communications"
  ON public.communication_history FOR ALL
  USING (has_any_role(auth.uid(), ARRAY['ADMIN'::app_role, 'DIRETORIA'::app_role, 'FINANCEIRO'::app_role, 'SECRETARIA'::app_role]));

CREATE POLICY "Finance can view communications"
  ON public.communication_history FOR SELECT
  USING (has_any_role(auth.uid(), ARRAY['ADMIN'::app_role, 'DIRETORIA'::app_role, 'FINANCEIRO'::app_role, 'SECRETARIA'::app_role]));

-- scheduled_reminders
ALTER TABLE public.scheduled_reminders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Finance can manage reminders"
  ON public.scheduled_reminders FOR ALL
  USING (has_any_role(auth.uid(), ARRAY['ADMIN'::app_role, 'DIRETORIA'::app_role, 'FINANCEIRO'::app_role, 'SECRETARIA'::app_role]));

CREATE POLICY "Finance can view reminders"
  ON public.scheduled_reminders FOR SELECT
  USING (has_any_role(auth.uid(), ARRAY['ADMIN'::app_role, 'DIRETORIA'::app_role, 'FINANCEIRO'::app_role, 'SECRETARIA'::app_role]));

-- =====================================================
-- TRIGGERS para updated_at
-- =====================================================
CREATE TRIGGER update_payment_agreements_updated_at
  BEFORE UPDATE ON public.payment_agreements
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();
